services:
  postgres:
    image: postgres:17-alpine
    container_name: brainmap-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT_EXTERNAL}:${DB_PORT_INTERNAL}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    restart: unless-stopped

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: brainmap-go-backend
    ports:
      - "${BACKEND_PORT_EXTERNAL}:${BACKEND_PORT_INTERNAL}"
    environment:
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT_INTERNAL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - APP_PORT=${BACKEND_PORT_INTERNAL}
      - REQUIRE_AUTH=${REQUIRE_AUTH}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
